# syntax=docker/dockerfile:1-labs
FROM node:22-alpine AS builder
WORKDIR /app
ENV VITE_API_URL="/api"
COPY --exclude=frontend/patrol_routes/.env* --exclude=backend --exclude=ml . .
WORKDIR /app/frontend/patrol_routes
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/patrol_routes/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
